# Generated by Django 4.2.1 on 2023-06-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_company_employees_departments_and_more'),
        ('extra_hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_hours',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
            preserve_default=False,
        ),
    ]
